name = "gkl-fantasy-analytics"
main = "worker.js"
compatibility_date = "2024-01-01"

# Account details (update with your CloudFlare account ID)
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"

# Environment variables (set these in CloudFlare dashboard or via wrangler secret)
# [vars]
# ENVIRONMENT = "production"

# Scheduled triggers (cron format in UTC)
# 6AM ET = 11AM UTC (EDT) or 10AM UTC (EST)
# 1PM ET = 6PM UTC (EDT) or 5PM UTC (EST) 
# 10PM ET = 3AM UTC next day (EDT) or 2AM UTC next day (EST)
[triggers]
crons = [
  "0 10 * * *",  # 6AM ET (EST)
  "0 17 * * *",  # 1PM ET (EST)
  "0 2 * * *"    # 10PM ET (EST, runs at 2AM UTC next day)
]

# KV namespace for storing state (optional)
# [[kv_namespaces]]
# binding = "STATE"
# id = "YOUR_KV_NAMESPACE_ID"

# Durable Objects (optional, for more complex state management)
# [[durable_objects.bindings]]
# name = "REFRESH_STATE"
# class_name = "RefreshState"
# script_name = "worker"

# Routes (optional, if you want to expose HTTP endpoints)
# [[routes]]
# pattern = "analytics.yourdomain.com/*"
# zone_name = "yourdomain.com"

# Development settings
[dev]
port = 8787
local_protocol = "http"

# Build settings
[build]
command = ""
watch_paths = ["worker.js"]

# Compatibility flags
compatibility_flags = []

# Usage model
usage_model = "bundled"